version: '3.8'

services:
  nginx-server:
    build: ./requirements/nginx
    image: nginx-server
    container_name: nginx-server
    ports:
      - 443:443

  maria-database:
    build: ./requirements/mariadb
    image: maria-database
    container_name: maria-database
